AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
    Environment:
        Type: String
#     BucketName:
#         Type: String
#     CodeKey:
#         Type: String
Resources:
  malwarechecker:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub malwarechecker-${Environment}
      Handler: malwarechecker.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess  
      CodeUri: src/malwarechecker.py
      Environment:
        Variables:
          TABLE_NAME: !Ref MalwareUrlsTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /urlinfo/1/{url}
            Method: get    
  feedupdate:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub feedupdate-${Environment}
      Handler: feedupdate.handler
      Runtime: python2.7
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess  
      CodeUri: src/feedupdate.py
      Environment:
        Variables:
          TABLE_NAME: !Ref MalwareUrlsTable 
          FEED_FILE_NAME: malware_url.csv
          BUCKET_NAME: !Ref malwareurlsfeedupdatebucket

      # Events:
      #   S3CreateObject:
      #     Type: s3
      #     Properties:
      #       Bucket: !Ref malwareurlsfeedupdatebucket
      #       Events: s3:S3CreateObject:* 
  MalwareUrlsTable:
     Type: AWS::DynamoDB::Table
     Properties: 
       AttributeDefinitions: 
         - AttributeName: malwareURLs
           AttributeType: S
       KeySchema: 
         - AttributeName: malwareURLs
           KeyType: HASH
       ProvisionedThroughput: 
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
  malwareurlsfeedupdatebucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     PolicyDocument:
  #       Statement:
  #         - Sid: PublicReadForGetBucketObjects
  #           Effect: Allow
  #           Principal: '*'
  #           Action: s3:GetObject
  #           Resource: !Join
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref malwareurlsfeedupdatebucket
  #               - /*
      
       
    